apiVersion: v2
description: common
type: application
name: common
version: 1.0.3
appVersion: 3.2.0
kubeVersion: '>=1.17.0-0'
dependencies:
  - name: common
    version: 3.2.0
    repository: https://library-charts.k8s-at-home.com
