{{- if .Values.metrics.enabled -}}
apiVersion: v1
kind: Service
metadata:
{{- if .Values.metrics.service.annotations }}
  annotations: {{ toYaml .Values.metrics.service.annotations | nindent 4 }}
{{- end }}
  labels:
    {{- include "generic.labels" . | nindent 4 }}
  {{- if .Values.metrics.service.labels }}
    {{- toYaml .Values.metrics.service.labels | nindent 4 }}
  {{- end }}
  name: {{ include "generic.fullname" . }}-metrics
spec:
  type: {{ .Values.metrics.service.type }}
{{- if .Values.metrics.service.clusterIP }}
  clusterIP: {{ .Values.metrics.service.clusterIP }}
{{- end }}
{{- if .Values.metrics.service.externalIPs }}
  externalIPs: {{ toYaml .Values.metrics.service.externalIPs | nindent 4 }}
{{- end }}
{{- if .Values.metrics.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.metrics.service.loadBalancerIP }}
{{- end }}
{{- if .Values.metrics.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{ toYaml .Values.metrics.service.loadBalancerSourceRanges | nindent 4 }}
{{- end }}
{{- if .Values.metrics.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.metrics.service.externalTrafficPolicy }}
{{- end }}
  ports:
    - name: metrics
      port: {{ .Values.metrics.service.servicePort }}
      targetPort: metrics
    {{- $setNodePorts := (or (eq .Values.metrics.service.type "NodePort") (eq .Values.metrics.service.type "LoadBalancer")) }}
    {{- if (and $setNodePorts (not (empty .Values.metrics.service.nodePort))) }}
      nodePort: {{ .Values.metrics.service.nodePort }}
    {{- end }}
  selector:
    {{- include "generic.selectorLabels" . | nindent 4 }}
{{- end }}