image:
  repository: ghcr.io/alexanderbabel/database-s3-backup
  tag: 1.3.3
  pullPolicy: IfNotPresent

labels: {}
annotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000

securityContext:
  capabilities:
    drop:
      - SETPCAP
      - MKNOD
      - AUDIT_WRITE
      - CHOWN
      - NET_RAW
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - SETFCAP
  readOnlyRootFilesystem: true

cronjob:
  enabled: false
  schedule: "0 * * * *"
  backoffLimit: 0
  startingDeadlineSeconds: 120
  activeDeadlineSeconds: 3300
  concurrencyPolicy: Forbid
  restartPolicy: Never

enableServiceLinks: false
automountServiceAccountToken: false

volumeMounts:
  - name: backup
    subPath: gnupg
    mountPath: /.gnupg
  - name: backup
    subPath: backup
    mountPath: /backup

volumes:
  - name: backup
    emptyDir: {}

credentials:
  bucketName: ""
  accessKeyId: ""
  secretAccessKey: ""
  endpoint: ""

databases:
  - backupName: db1
    databaseUrl: mongodb://user:pass@host:port/database?authSource=src
    # databaseUrl: postgresql://user:pass@host:port/database
    # databaseUrl: mysql://user:pass@host:port/database
    encryptionKey: ""
