{{- define "database.yaml" }}
user: "{{ .Values.postgresql.username }}"
password: "{{ .Values.postgresql.password }}"
database: "{{ .Values.postgresql.database }}"        
{{- if .Values.postgresql.enabled }}
host: "{{ include "matrix.fullname" . }}-postgresql"
port: "5432"
{{- else }}
host: "{{ .Values.postgresql.hostname }}"
port: "{{ .Values.postgresql.port }}"
{{- end }}
sslmode: {{ .Values.postgresql.sslMode }}
{{- end }}